### ISSUE TITLE
plujain-ramp crashes Ardour 

### ISSUE THREAD

**Issue by sub26nico** [Houston4444/plujain-ramp#2]
If it is added to a Bus . To reproduce : 
1) Open a project in Ardour
2) Add a Audio Bus 
3) Insert plujain ramp in the bus

**Comment by Houston4444** [comment]
I can't reproduce it. I think that you tried to add a plugin instance in an ardour session that has already had a previous version of plujain ramp.

Bon en gros, ça ne plante pas chez moi, et je pense que si tu insères le greffon dans une session ardour neuve, y a pas de raison particulière pour que ça plante. Je pense que la session que tu utilises avais utilisé une version antérieure du plujain ramp (qui auparavant contenait des paramètres qui ont été supprimés du Plujain Ramp, mais conservés dans le Plujain Ramp Live).

**Comment by sub26nico** [comment]
Strange....Today it's working....I created a new session yesterday, not an older. And tried many times, it crashed every times. But this morning, reading your answer, I try the same things, creating new session and add plujain ramp on busses, no more crashes. Then open my yesterday's session, it is working too...
I close here.
